function cfg = scenario_default()
% Scenario de reference pour runWorkflow — definit COMMENT simuler (duree, figures, exports).
% Ne contient pas de parametres physiques (voir scripts/config/params_*.m pour ca).
% Copier et renommer pour creer un nouveau scenario.

cfg = struct( ...
    'modelName',          'model/Modele_LQR_6DOF.slx', ...
    'stopTime',           10, ...
    'runParameters',      true, ...
    'runGraphique',       true, ...
    'runMouvement',       false, ...
    'runStability',       true, ...
    'reportInstability',  true, ...
    'openModel',          false, ...
    'showFigures',        true, ...
    'saveFigures',        false, ...
    'figureOutputDir',    'docs/figures' ...
);
end
