function config_selector()
% Fenetre de selection de la calibration et de la trajectoire active.
%
% Usage:
%   config_selector()
%
% Permet de changer la calibration et la trajectoire puis lancer une
% simulation sans taper de commandes dans la Command Window.

fig = uifigure('Name', 'Configuration AUV ASUQTR', ...
    'Position', [200 200 320 290], ...
    'Resize', 'off');

% --- Titre ---
uilabel(fig, ...
    'Text', 'Configuration de la simulation', ...
    'Position', [20 255 280 22], ...
    'FontWeight', 'bold', 'FontSize', 12);

% --- Section calibration ---
uilabel(fig, ...
    'Text', 'Calibration physique (AUV_Params.sldd)', ...
    'Position', [20 228 280 18], ...
    'FontColor', [0.4 0.4 0.4], 'FontSize', 10);

ddCalib = uidropdown(fig, ...
    'Items',     {'Nominal — valeurs mesurees 2026 (defaut)', ...
                  'Emile  — variante inertie Emile', ...
                  'Originaux — modele theorique initial'}, ...
    'ItemsData', {'nominal', 'emile', 'originaux'}, ...
    'Position',  [20 190 280 32], ...
    'FontSize',  11);

% --- Section trajectoire ---
uilabel(fig, ...
    'Text', 'Trajectoire de reference', ...
    'Position', [20 162 280 18], ...
    'FontColor', [0.4 0.4 0.4], 'FontSize', 10);

ddTraj = uidropdown(fig, ...
    'Items',     {'1 — Carre (defaut)', ...
                  '2 — Cercle', ...
                  '3 — Sphere (placeholder)'}, ...
    'ItemsData', {int32(1), int32(2), int32(3)}, ...
    'Position',  [20 124 280 32], ...
    'FontSize',  11);

% Initialiser le menu au choix courant du workspace (defaut 1 si absent)
try
    trajActuelle = int32(evalin('base', 'TRAJECTOIRE'));
    if ismember(trajActuelle, [int32(1) int32(2) int32(3)])
        ddTraj.Value = trajActuelle;
    end
catch
end

% --- Bouton : Appliquer seulement ---
uibutton(fig, ...
    'Text', 'Appliquer la configuration', ...
    'Position', [20 74 280 36], ...
    'FontSize', 11, ...
    'ButtonPushedFcn', @(~,~) appliquer(ddCalib.Value, ddTraj.Value, false));

% --- Bouton : Appliquer + Simuler ---
uibutton(fig, ...
    'Text', 'Appliquer et lancer la simulation', ...
    'Position', [20 28 280 36], ...
    'FontSize', 11, ...
    'BackgroundColor', [0.2 0.5 0.9], ...
    'FontColor', 'white', ...
    'ButtonPushedFcn', @(~,~) appliquer(ddCalib.Value, ddTraj.Value, true));

    function appliquer(variant, trajVal, simuler)
        try
            set_config(variant);
            assignin('base', 'TRAJECTOIRE', int32(trajVal));
        catch err
            uialert(fig, err.message, 'Erreur', 'Icon', 'error');
            return;
        end

        if simuler
            close(fig);
            runWorkflow();
        else
            uialert(fig, ...
                sprintf('Calibration : params_%s\nTrajectoire : %d', variant, trajVal), ...
                'OK', 'Icon', 'success');
        end
    end

end
