function config_selector()
% Fenetre de selection de la calibration active du sous-marin.
%
% Usage:
%   config_selector()
%
% Permet de changer la calibration et lancer une simulation sans
% taper de commandes dans la Command Window.

fig = uifigure('Name', 'Calibration AUV ASUQTR', ...
    'Position', [200 200 320 220], ...
    'Resize', 'off');

% --- Titre ---
uilabel(fig, ...
    'Text', 'Selectionner une calibration physique', ...
    'Position', [20 180 280 22], ...
    'FontWeight', 'bold', 'FontSize', 12);

% --- Description ---
uilabel(fig, ...
    'Text', 'Parametres charges dans AUV_Params.sldd', ...
    'Position', [20 158 280 18], ...
    'FontColor', [0.4 0.4 0.4], 'FontSize', 10);

% --- Menu deroulant ---
dd = uidropdown(fig, ...
    'Items',     {'Nominal — valeurs mesurees 2026 (defaut)', ...
                  'Emile  — variante inertie Emile', ...
                  'Originaux — modele theorique initial'}, ...
    'ItemsData', {'nominal', 'emile', 'originaux'}, ...
    'Position',  [20 115 280 32], ...
    'FontSize',  11);

% --- Bouton : Appliquer seulement ---
uibutton(fig, ...
    'Text', 'Appliquer la calibration', ...
    'Position', [20 68 280 36], ...
    'FontSize', 11, ...
    'ButtonPushedFcn', @(~,~) appliquer(dd.Value, false));

% --- Bouton : Appliquer + Simuler ---
uibutton(fig, ...
    'Text', 'Appliquer et lancer la simulation', ...
    'Position', [20 22 280 36], ...
    'FontSize', 11, ...
    'BackgroundColor', [0.2 0.5 0.9], ...
    'FontColor', 'white', ...
    'ButtonPushedFcn', @(~,~) appliquer(dd.Value, true));

    function appliquer(variant, simuler)
        try
            set_config(variant);
            if simuler
                close(fig);
                runWorkflow();
            else
                uialert(fig, ...
                    sprintf('Calibration appliquee : params_%s', variant), ...
                    'OK', 'Icon', 'success');
            end
        catch err
            uialert(fig, err.message, 'Erreur', 'Icon', 'error');
        end
    end

end
